### ISSUE TITLE
ping test is not working after Keepalived deployed

### ISSUE THREAD

**Issue by GunSik2** [CrossentCloud/x1-svc-deploy-repo#2]
- sysctl -p 명령을 수동으로 해야 반영됨

**Comment by GunSik2** [comment]
ansible 배포 후 interface 명시적으로 등록 후 ping 가능 (대전개발환겨에서)
````
$ sudo ifconfig ens3:1 10.2.1.11 up
```

**Comment by gustnor** [comment]
[오류 원인]
- haproxy가 설치 되지 않은 상태에서 keepalived 설치시 keepalived.conf에 chk_haproxy 로직을 수행하다 오류 발생하여 interface에 vip 할당을 못함

[keepalived 디버그 방법]
- 실행 : keepalived -f /etc/keepalived/keepalived.conf --dont-fork --log-console --log-detail
- 오류메세지 : VRRP_Instance(VIS_1) Now in FAULT state

**Comment by GunSik2** [comment]
VIP 배정 기준을 haproxy 프로세스 기준으로 수행하기 떄문에,
Haproxy 프로세스가 설치되기 전에는 VIP가 어느쪽에도 배정되지 않는 것이 정상입니다.

이상이 없으므로 종료 처리합니다.
